In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("✅ Libraries loaded!")

✅ Libraries loaded!

In [3]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv"
df = pd.read_csv(url)
print("Shape:", df.shape)
df.head(10)

Shape: (90, 17)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857
5,6,2014-01-06,Falcon 9,3325.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1005,-80.577366,28.561857
6,7,2014-04-18,Falcon 9,2296.000000,ISS,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1006,-80.577366,28.561857
7,8,2014-07-14,Falcon 9,1316.000000,LEO,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1007,-80.577366,28.561857
8,9,2014-08-05,Falcon 9,4535.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1008,-80.577366,28.561857
9,10,2014-09-07,Falcon 9,4428.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1011,-80.577366,28.561857

In [4]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv"
df = pd.read_csv(url)
print("Shape:", df.shape)
df.head(10)

Shape: (90, 17)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857
5,6,2014-01-06,Falcon 9,3325.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1005,-80.577366,28.561857
6,7,2014-04-18,Falcon 9,2296.000000,ISS,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1006,-80.577366,28.561857
7,8,2014-07-14,Falcon 9,1316.000000,LEO,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1007,-80.577366,28.561857
8,9,2014-08-05,Falcon 9,4535.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1008,-80.577366,28.561857
9,10,2014-09-07,Falcon 9,4428.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1011,-80.577366,28.561857

In [5]:
# Calculate percentage of missing values
print("Missing values percentage:")
print(df.isnull().sum()/len(df)*100)

Missing values percentage:
FlightNumber       0.000000
Date               0.000000
BoosterVersion     0.000000
PayloadMass        0.000000
Orbit              0.000000
LaunchSite         0.000000
Outcome            0.000000
Flights            0.000000
GridFins           0.000000
Reused             0.000000
Legs               0.000000
LandingPad        28.888889
Block              0.000000
ReusedCount        0.000000
Serial             0.000000
Longitude          0.000000
Latitude           0.000000
dtype: float64

In [6]:
print("Data types:")
print(df.dtypes)
print("\nValue counts for each column:")
df.apply(pd.Series.value_counts)

Data types:
FlightNumber        int64
Date               object
BoosterVersion     object
PayloadMass       float64
Orbit              object
LaunchSite         object
Outcome            object
Flights             int64
GridFins             bool
Reused               bool
Legs                 bool
LandingPad         object
Block             float64
ReusedCount         int64
Serial             object
Longitude         float64
Latitude          float64
dtype: object

Value counts for each column:

TypeError: '<' not supported between instances of 'str' and 'int'

In [7]:
print("Data types:")
print(df.dtypes)

Data types:
FlightNumber        int64
Date               object
BoosterVersion     object
PayloadMass       float64
Orbit              object
LaunchSite         object
Outcome            object
Flights             int64
GridFins             bool
Reused               bool
Legs                 bool
LandingPad         object
Block             float64
ReusedCount         int64
Serial             object
Longitude         float64
Latitude          float64
dtype: object

In [8]:
landing_outcomes = df['Outcome'].value_counts()
print("Landing Outcomes:")
print(landing_outcomes)

Landing Outcomes:
Outcome
True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: count, dtype: int64

In [9]:
bad_outcomes = set(landing_outcomes.keys()[[1,3,5,6,7]])
print("Bad outcomes:")
print(bad_outcomes)

Bad outcomes:
{'False ASDS', 'None None', 'False Ocean', 'None ASDS', 'False RTLS'}

In [10]:
landing_class = [0 if x in bad_outcomes else 1 for x in df['Outcome']]
df['Class'] = landing_class
print(df[['Outcome','Class']].head(20))
print("\nSuccess rate:", df['Class'].mean())

        Outcome  Class
0     None None      0
1     None None      0
2     None None      0
3   False Ocean      0
4     None None      0
5     None None      0
6    True Ocean      1
7    True Ocean      1
8     None None      0
9     None None      0
10  False Ocean      0
11   False ASDS      0
12   True Ocean      1
13   False ASDS      0
14    None None      0
15    None ASDS      0
16    True RTLS      1
17   False ASDS      0
18   False ASDS      0
19    True ASDS      1

Success rate: 0.6666666666666666

In [11]:
df.to_csv('dataset_part_2.csv', index=False)
import shutil
shutil.copy('dataset_part_2.csv', '/content/drive/MyDrive/dataset_part_2.csv')
print("✅ Saved! Shape:", pd.read_csv('dataset_part_2.csv').shape)
df.head(5)

✅ Saved! Shape: (90, 18)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude,Class
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857,0
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857,0
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857,0
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093,0
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857,0

In [12]:
bad_outcomes = set(landing_outcomes.keys()[[1,3,5,6,7]])
print("Bad outcomes:")
print(bad_outcomes)

Bad outcomes:
{'False ASDS', 'None None', 'False Ocean', 'None ASDS', 'False RTLS'}

In [13]:
landing_class = [0 if x in bad_outcomes else 1 for x in df['Outcome']]
df['Class'] = landing_class
print(df[['Outcome','Class']].head(20))
print("\nSuccess rate:", df['Class'].mean())

        Outcome  Class
0     None None      0
1     None None      0
2     None None      0
3   False Ocean      0
4     None None      0
5     None None      0
6    True Ocean      1
7    True Ocean      1
8     None None      0
9     None None      0
10  False Ocean      0
11   False ASDS      0
12   True Ocean      1
13   False ASDS      0
14    None None      0
15    None ASDS      0
16    True RTLS      1
17   False ASDS      0
18   False ASDS      0
19    True ASDS      1

Success rate: 0.6666666666666666

In [14]:
df.to_csv('dataset_part_2.csv', index=False)
import shutil
shutil.copy('dataset_part_2.csv', '/content/drive/MyDrive/dataset_part_2.csv')
print("✅ Saved! Shape:", pd.read_csv('dataset_part_2.csv').shape)
df.head(5)

✅ Saved! Shape: (90, 18)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude,Class
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857,0
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857,0
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857,0
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093,0
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857,0

In [15]:
print("Class value counts:")
print(df['Class'].value_counts())
print("\nSuccess rate:", df['Class'].mean())
print("Total launches:", len(df))

Class value counts:
Class
1    60
0    30
Name: count, dtype: int64

Success rate: 0.6666666666666666
Total launches: 90

In [16]:
df.to_csv('dataset_part_2.csv', index=False)
import shutil
shutil.copy('dataset_part_2.csv', '/content/drive/MyDrive/dataset_part_2.csv')
print("✅ Saved! Shape:", pd.read_csv('dataset_part_2.csv').shape)

✅ Saved! Shape: (90, 18)